//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPhonos.UPnP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UPnP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UPnP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenPhonos.UPnP.UPnP", typeof(UPnP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutButton_Label {
            get {
                return ResourceManager.GetString("AboutButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version: {0}
        ///Sonos Version: {1}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Sonos Favorite....
        /// </summary>
        internal static string AddingFavorite {
            get {
                return ResourceManager.GetString("AddingFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string AlarmEditAlarm_Text {
            get {
                return ResourceManager.GetString("AlarmEditAlarm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string AlarmEditDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("AlarmEditDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AlarmEditDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("AlarmEditDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string AlarmEditDuration_Text {
            get {
                return ResourceManager.GetString("AlarmEditDuration.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string AlarmEditDuration120_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration120.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        internal static string AlarmEditDuration15_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration15.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        internal static string AlarmEditDuration180_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration180.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string AlarmEditDuration30_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration30.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        internal static string AlarmEditDuration45_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration45.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string AlarmEditDuration60_Content {
            get {
                return ResourceManager.GetString("AlarmEditDuration60.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limit.
        /// </summary>
        internal static string AlarmEditDurationNone_Content {
            get {
                return ResourceManager.GetString("AlarmEditDurationNone.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include grouped rooms.
        /// </summary>
        internal static string AlarmEditGrouped_Content {
            get {
                return ResourceManager.GetString("AlarmEditGrouped.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string AlarmEditMusic_Text {
            get {
                return ResourceManager.GetString("AlarmEditMusic.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once Only.
        /// </summary>
        internal static string AlarmEditOnceOnly_Content {
            get {
                return ResourceManager.GetString("AlarmEditOnceOnly.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string AlarmEditRoom_Text {
            get {
                return ResourceManager.GetString("AlarmEditRoom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string AlarmEditSchedule_Text {
            get {
                return ResourceManager.GetString("AlarmEditSchedule.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string AlarmEditTime_Text {
            get {
                return ResourceManager.GetString("AlarmEditTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string AlarmEditVolume_Text {
            get {
                return ResourceManager.GetString("AlarmEditVolume.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string AlarmListDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("AlarmListDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Alarm.
        /// </summary>
        internal static string AlarmListDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("AlarmListDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        internal static string AlarmListDialog_Title {
            get {
                return ResourceManager.GetString("AlarmListDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Music.
        /// </summary>
        internal static string AlarmMusic {
            get {
                return ResourceManager.GetString("AlarmMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        internal static string AlarmsMenuItem {
            get {
                return ResourceManager.GetString("AlarmsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string AlarmSummaryDaily {
            get {
                return ResourceManager.GetString("AlarmSummaryDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        internal static string AlarmSummaryOnce {
            get {
                return ResourceManager.GetString("AlarmSummaryOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Alarm.
        /// </summary>
        internal static string AlarmTitleAdd {
            get {
                return ResourceManager.GetString("AlarmTitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Alarm.
        /// </summary>
        internal static string AlarmTitleEdit {
            get {
                return ResourceManager.GetString("AlarmTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tracks.
        /// </summary>
        internal static string AllTracks {
            get {
                return ResourceManager.GetString("AllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Preview has expired. Thank you everyone for your feedback, you can now get the full version of Phonos Universal from the Store.
        /// </summary>
        internal static string AppExpired {
            get {
                return ResourceManager.GetString("AppExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance_Text {
            get {
                return ResourceManager.GetString("Balance.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string BalanceL_Text {
            get {
                return ResourceManager.GetString("BalanceL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string BalanceR_Text {
            get {
                return ResourceManager.GetString("BalanceR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        internal static string Bass_Text {
            get {
                return ResourceManager.GetString("Bass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Group....
        /// </summary>
        internal static string ChangingGroup {
            get {
                return ResourceManager.GetString("ChangingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composers.
        /// </summary>
        internal static string Composers {
            get {
                return ResourceManager.GetString("Composers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfade is off.
        /// </summary>
        internal static string CrossfadeOff {
            get {
                return ResourceManager.GetString("CrossfadeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfade is on.
        /// </summary>
        internal static string CrossfadeOn {
            get {
                return ResourceManager.GetString("CrossfadeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove a song from the queue, drag it over this icon..
        /// </summary>
        internal static string DeleteTrackHowTo {
            get {
                return ResourceManager.GetString("DeleteTrackHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DeviceEQDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("DeviceEQDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics:.
        /// </summary>
        internal static string DiagnosticsTo {
            get {
                return ResourceManager.GetString("DiagnosticsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Dialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("Dialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislike.
        /// </summary>
        internal static string DislikeButton_Label {
            get {
                return ResourceManager.GetString("DislikeButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string EditGroup_PrimaryButtonText {
            get {
                return ResourceManager.GetString("EditGroup.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditGroup_SecondaryButtonText {
            get {
                return ResourceManager.GetString("EditGroup.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Rooms.
        /// </summary>
        internal static string EditGroup_Title {
            get {
                return ResourceManager.GetString("EditGroup.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (We will not reply to this email unless you ask us to)..
        /// </summary>
        internal static string EmailNoReply {
            get {
                return ResourceManager.GetString("EmailNoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to: support@phonos.org.
        /// </summary>
        internal static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string EQReset_Content {
            get {
                return ResourceManager.GetString("EQReset.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play &apos;{0}&apos; - network connection speed insufficient to maintain playback buffer.
        /// </summary>
        internal static string ErrorBuffering {
            get {
                return ResourceManager.GetString("ErrorBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play &apos;{0}&apos; - unable to connect to {1}.
        /// </summary>
        internal static string ErrorCantReachServer {
            get {
                return ResourceManager.GetString("ErrorCantReachServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play &apos;{0}&apos; - cannot find {1}.
        /// </summary>
        internal static string ErrorCantResolveName {
            get {
                return ResourceManager.GetString("ErrorCantResolveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting items.
        /// </summary>
        internal static string ErrorGettingItems {
            get {
                return ResourceManager.GetString("ErrorGettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play &apos;{0}&apos; - the connection to {1} was lost.
        /// </summary>
        internal static string ErrorLostConnection {
            get {
                return ResourceManager.GetString("ErrorLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play &apos;{0}&apos; - .
        /// </summary>
        internal static string ErrorUnableToPlay {
            get {
                return ResourceManager.GetString("ErrorUnableToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Favorite. There are no empty favorites remaining. You can remove existing Sonos Favorites to make room for new ones..
        /// </summary>
        internal static string FavoritesFull {
            get {
                return ResourceManager.GetString("FavoritesFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos players found, but a firewall is blocking network &apos;{0}&apos;.
        /// </summary>
        internal static string Firewall_Blocking {
            get {
                return ResourceManager.GetString("Firewall_Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Volume.
        /// </summary>
        internal static string FixedVolume_Text {
            get {
                return ResourceManager.GetString("FixedVolume.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ({0}).
        /// </summary>
        internal static string Format_Unknown {
            get {
                return ResourceManager.GetString("Format_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Digital 5.1.
        /// </summary>
        internal static string FormatDolby {
            get {
                return ResourceManager.GetString("FormatDolby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolby Digital 2.0.
        /// </summary>
        internal static string FormatDolby2 {
            get {
                return ResourceManager.GetString("FormatDolby2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signal.
        /// </summary>
        internal static string FormatNoSignal {
            get {
                return ResourceManager.GetString("FormatNoSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Burst.
        /// </summary>
        internal static string FormatPauseBurst {
            get {
                return ResourceManager.GetString("FormatPauseBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence.
        /// </summary>
        internal static string FormatSilence {
            get {
                return ResourceManager.GetString("FormatSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string FormatStereo {
            get {
                return ResourceManager.GetString("FormatStereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported.
        /// </summary>
        internal static string FormatUnsupported {
            get {
                return ResourceManager.GetString("FormatUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Music Library.
        /// </summary>
        internal static string FromMusicLibrary {
            get {
                return ResourceManager.GetString("FromMusicLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Volume.
        /// </summary>
        internal static string GroupVolume_Text {
            get {
                return ResourceManager.GetString("GroupVolume.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Playlists.
        /// </summary>
        internal static string ImportedPlaylists {
            get {
                return ResourceManager.GetString("ImportedPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem indexing music library {0}.
        /// </summary>
        internal static string Indexing_Problem {
            get {
                return ResourceManager.GetString("Indexing_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal failure in network API.
        /// </summary>
        internal static string InternalNetworkFailure {
            get {
                return ResourceManager.GetString("InternalNetworkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string LikeButton_Label {
            get {
                return ResourceManager.GetString("LikeButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Radio ({0}).
        /// </summary>
        internal static string Local_Radio {
            get {
                return ResourceManager.GetString("Local_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudness.
        /// </summary>
        internal static string Loudness_Text {
            get {
                return ResourceManager.GetString("Loudness.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string MoreButton_Label {
            get {
                return ResourceManager.GetString("MoreButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See http://phonos.org/windows/support.html.
        ///For further assistance email support@phonos.org
        ///The clipboard has been filled with additional technical information, please include that..
        /// </summary>
        internal static string MoreHelp {
            get {
                return ResourceManager.GetString("MoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MusicAbout {
            get {
                return ResourceManager.GetString("MusicAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email us.
        /// </summary>
        internal static string MusicEmailUs {
            get {
                return ResourceManager.GetString("MusicEmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook page.
        /// </summary>
        internal static string MusicFacebookPage {
            get {
                return ResourceManager.GetString("MusicFacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help via Email.
        /// </summary>
        internal static string MusicHelpEmail {
            get {
                return ResourceManager.GetString("MusicHelpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Library.
        /// </summary>
        internal static string MusicLibraryTitle {
            get {
                return ResourceManager.GetString("MusicLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line-In.
        /// </summary>
        internal static string MusicLineIn {
            get {
                return ResourceManager.GetString("MusicLineIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Library.
        /// </summary>
        internal static string MusicMusicLibrary {
            get {
                return ResourceManager.GetString("MusicMusicLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Source.
        /// </summary>
        internal static string MusicMusicSource {
            get {
                return ResourceManager.GetString("MusicMusicSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string MusicNoItemsFound {
            get {
                return ResourceManager.GetString("MusicNoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Alarm Music.
        /// </summary>
        internal static string MusicPickerDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("MusicPickerDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MusicPickerDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("MusicPickerDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string MusicReview {
            get {
                return ResourceManager.GetString("MusicReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string MusicServiceLanguage {
            get {
                return ResourceManager.GetString("MusicServiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MusicSettings {
            get {
                return ResourceManager.GetString("MusicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos Favorites.
        /// </summary>
        internal static string MusicSonosFavorites {
            get {
                return ResourceManager.GetString("MusicSonosFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos Playlists.
        /// </summary>
        internal static string MusicSonosPlaylists {
            get {
                return ResourceManager.GetString("MusicSonosPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string MusicStarting {
            get {
                return ResourceManager.GetString("MusicStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light/Dark Theme.
        /// </summary>
        internal static string MusicThemeOption {
            get {
                return ResourceManager.GetString("MusicThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string MusicTV {
            get {
                return ResourceManager.GetString("MusicTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Music Library Now.
        /// </summary>
        internal static string MusicUpdateLibrary {
            get {
                return ResourceManager.GetString("MusicUpdateLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Radio Shows.
        /// </summary>
        internal static string MyRadioShows {
            get {
                return ResourceManager.GetString("MyRadioShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Radio Stations.
        /// </summary>
        internal static string MyRadioStations {
            get {
                return ResourceManager.GetString("MyRadioStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tracks.
        /// </summary>
        internal static string N_Tracks {
            get {
                return ResourceManager.GetString("N_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login information is not valid, check using an official Sonos app.
        /// </summary>
        internal static string NeedReath {
            get {
                return ResourceManager.GetString("NeedReath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network &apos;{0}&apos; contains no players.
        /// </summary>
        internal static string Network_ContainsNoPlayers {
            get {
                return ResourceManager.GetString("Network_ContainsNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos players found, but the network &apos;{0}&apos; may not compatible with this application.
        /// </summary>
        internal static string Network_NotCompatible {
            get {
                return ResourceManager.GetString("Network_NotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos players found, but the network &apos;{0}&apos; is not Private, please change it.
        /// </summary>
        internal static string Network_NotPrivate {
            get {
                return ResourceManager.GetString("Network_NotPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown reason.
        /// </summary>
        internal static string NetworkProblemUnknown {
            get {
                return ResourceManager.GetString("NetworkProblemUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton_Label {
            get {
                return ResourceManager.GetString("NextButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Sound is Off.
        /// </summary>
        internal static string NightModeOff {
            get {
                return ResourceManager.GetString("NightModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Sound is On.
        /// </summary>
        internal static string NightModeOn {
            get {
                return ResourceManager.GetString("NightModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No music].
        /// </summary>
        internal static string NoMusic {
            get {
                return ResourceManager.GetString("NoMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sonos players found.
        /// </summary>
        internal static string NoPlayersFound {
            get {
                return ResourceManager.GetString("NoPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable networks found.
        /// </summary>
        internal static string NoSuitableNetworksFound {
            get {
                return ResourceManager.GetString("NoSuitableNetworksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to Wi-Fi.
        /// </summary>
        internal static string NotConnectedToWiFi {
            get {
                return ResourceManager.GetString("NotConnectedToWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not properly connected to network &apos;{0}&apos;.
        /// </summary>
        internal static string NotProperlyConnectedTo_Network {
            get {
                return ResourceManager.GetString("NotProperlyConnectedTo_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track [{0}/{1}].
        /// </summary>
        internal static string NP_Track_Counter {
            get {
                return ResourceManager.GetString("NP_Track_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string NPAlbum {
            get {
                return ResourceManager.GetString("NPAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string NPArtist {
            get {
                return ResourceManager.GetString("NPArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio In.
        /// </summary>
        internal static string NPAudioIn {
            get {
                return ResourceManager.GetString("NPAudioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string NPChannel {
            get {
                return ResourceManager.GetString("NPChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string NPInformation {
            get {
                return ResourceManager.GetString("NPInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NPNext {
            get {
                return ResourceManager.GetString("NPNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing.
        /// </summary>
        internal static string NPNothing {
            get {
                return ResourceManager.GetString("NPNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Now.
        /// </summary>
        internal static string NPOnNow {
            get {
                return ResourceManager.GetString("NPOnNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string NPRoom {
            get {
                return ResourceManager.GetString("NPRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string NPSource {
            get {
                return ResourceManager.GetString("NPSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string NPStation {
            get {
                return ResourceManager.GetString("NPStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string NPTrack {
            get {
                return ResourceManager.GetString("NPTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string NPTV {
            get {
                return ResourceManager.GetString("NPTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or a firewall is blocking incoming TCP port {0}.
        /// </summary>
        internal static string Or_Firewall {
            get {
                return ResourceManager.GetString("Or_Firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string PandoraBadCredentials {
            get {
                return ResourceManager.GetString("PandoraBadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pandora will play more tracks with similar musical qualities.
        /// </summary>
        internal static string PandoraMore {
            get {
                return ResourceManager.GetString("PandoraMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track won&apos;t play again on this station.
        /// </summary>
        internal static string PandoraNoMore {
            get {
                return ResourceManager.GetString("PandoraNoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseButton_Label {
            get {
                return ResourceManager.GetString("PauseButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was a problem playing that:
        ///.
        /// </summary>
        internal static string Playback_Problem {
            get {
                return ResourceManager.GetString("Playback_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PlayButton_Label {
            get {
                return ResourceManager.GetString("PlayButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Starting up].
        /// </summary>
        internal static string PlayerStartingUp {
            get {
                return ResourceManager.GetString("PlayerStartingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please PASTE here before sending.
        /// </summary>
        internal static string PleasePaste {
            get {
                return ResourceManager.GetString("PleasePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        internal static string PopupAddQueue {
            get {
                return ResourceManager.GetString("PopupAddQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PopupDelete {
            get {
                return ResourceManager.GetString("PopupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Sonos Favorites.
        /// </summary>
        internal static string PopupFavorite {
            get {
                return ResourceManager.GetString("PopupFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Next.
        /// </summary>
        internal static string PopupPlayNext {
            get {
                return ResourceManager.GetString("PopupPlayNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Now.
        /// </summary>
        internal static string PopupPlayNow {
            get {
                return ResourceManager.GetString("PopupPlayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Queue.
        /// </summary>
        internal static string PopupReplaceQueue {
            get {
                return ResourceManager.GetString("PopupReplaceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousButton_Label {
            get {
                return ResourceManager.GetString("PreviousButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue_Header {
            get {
                return ResourceManager.GetString("Queue.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string QueueAll_Text {
            get {
                return ResourceManager.GetString("QueueAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string QueueClearNo {
            get {
                return ResourceManager.GetString("QueueClearNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the queue?.
        /// </summary>
        internal static string QueueClearSure {
            get {
                return ResourceManager.GetString("QueueClearSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string QueueClearYes {
            get {
                return ResourceManager.GetString("QueueClearYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Error.
        /// </summary>
        internal static string QueueError {
            get {
                return ResourceManager.GetString("QueueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not in use).
        /// </summary>
        internal static string QueueNotInUse {
            get {
                return ResourceManager.GetString("QueueNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string QueueTitle {
            get {
                return ResourceManager.GetString("QueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio by TuneIn.
        /// </summary>
        internal static string RadioTitle {
            get {
                return ResourceManager.GetString("RadioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} account needs to be reauthorized using an official Sonos app.
        /// </summary>
        internal static string Reauth_Official {
            get {
                return ResourceManager.GetString("Reauth_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove song.
        /// </summary>
        internal static string RemoveSong {
            get {
                return ResourceManager.GetString("RemoveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat is off.
        /// </summary>
        internal static string RepeatOff {
            get {
                return ResourceManager.GetString("RepeatOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat all.
        /// </summary>
        internal static string RepeatOn {
            get {
                return ResourceManager.GetString("RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat song.
        /// </summary>
        internal static string RepeatOne {
            get {
                return ResourceManager.GetString("RepeatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms_Text {
            get {
                return ResourceManager.GetString("Rooms.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string RoomSelectAll_Content {
            get {
                return ResourceManager.GetString("RoomSelectAll.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name to save as.
        /// </summary>
        internal static string SaveQueue_PlaceholderText {
            get {
                return ResourceManager.GetString("SaveQueue.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveQueueDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SaveQueueDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SaveQueueDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("SaveQueueDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Queue.
        /// </summary>
        internal static string SaveQueueDialog_Title {
            get {
                return ResourceManager.GetString("SaveQueueDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0}.
        /// </summary>
        internal static string Search_Prompt {
            get {
                return ResourceManager.GetString("Search_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts.
        /// </summary>
        internal static string SearchHosts {
            get {
                return ResourceManager.GetString("SearchHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for your Sonos system....
        /// </summary>
        internal static string SearchingNetwork {
            get {
                return ResourceManager.GetString("SearchingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string SearchPeople {
            get {
                return ResourceManager.GetString("SearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string SearchPlaylists {
            get {
                return ResourceManager.GetString("SearchPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        internal static string SearchPodcasts {
            get {
                return ResourceManager.GetString("SearchPodcasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string SearchStations {
            get {
                return ResourceManager.GetString("SearchStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string SearchTags {
            get {
                return ResourceManager.GetString("SearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle is off.
        /// </summary>
        internal static string ShuffleOff {
            get {
                return ResourceManager.GetString("ShuffleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle is on.
        /// </summary>
        internal static string ShuffleOn {
            get {
                return ResourceManager.GetString("ShuffleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Timer ({0}).
        /// </summary>
        internal static string Sleep_Timer {
            get {
                return ResourceManager.GetString("Sleep_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string Sleep120 {
            get {
                return ResourceManager.GetString("Sleep120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        internal static string Sleep15 {
            get {
                return ResourceManager.GetString("Sleep15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string Sleep30 {
            get {
                return ResourceManager.GetString("Sleep30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        internal static string Sleep45 {
            get {
                return ResourceManager.GetString("Sleep45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string Sleep60 {
            get {
                return ResourceManager.GetString("Sleep60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SleepOff {
            get {
                return ResourceManager.GetString("SleepOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SleepTimerOff {
            get {
                return ResourceManager.GetString("SleepTimerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        internal static string Snooze10_Text {
            get {
                return ResourceManager.GetString("Snooze10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string Snooze120_Text {
            get {
                return ResourceManager.GetString("Snooze120.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        internal static string Snooze15_Text {
            get {
                return ResourceManager.GetString("Snooze15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string Snooze30_Text {
            get {
                return ResourceManager.GetString("Snooze30.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        internal static string Snooze45_Text {
            get {
                return ResourceManager.GetString("Snooze45.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        internal static string Snooze5_Text {
            get {
                return ResourceManager.GetString("Snooze5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string Snooze60_Text {
            get {
                return ResourceManager.GetString("Snooze60.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze for:.
        /// </summary>
        internal static string SnoozeTitle_Text {
            get {
                return ResourceManager.GetString("SnoozeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos Chime.
        /// </summary>
        internal static string SonosChime {
            get {
                return ResourceManager.GetString("SonosChime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonos system update version {0} is available from Sonos, you can use their official app to update your system..
        /// </summary>
        internal static string SonosSystemUpdate {
            get {
                return ResourceManager.GetString("SonosSystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot find {0}.
        /// </summary>
        internal static string Sorry_NoFind {
            get {
                return ResourceManager.GetString("Sorry_NoFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot find a player called {0}.
        /// </summary>
        internal static string Sorry_NoPlayer {
            get {
                return ResourceManager.GetString("Sorry_NoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} is not playable.
        /// </summary>
        internal static string Sorry_NotPlayable {
            get {
                return ResourceManager.GetString("Sorry_NotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the volume is fixed in the {0}.
        /// </summary>
        internal static string Sorry_VolumeFixed {
            get {
                return ResourceManager.GetString("Sorry_VolumeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Phonos crashed last time you ran it, will now send email so we can try and fix it.
        /// </summary>
        internal static string SorryCrashed {
            get {
                return ResourceManager.GetString("SorryCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Dave, I can&apos;t do that.
        /// </summary>
        internal static string SorryDave {
            get {
                return ResourceManager.GetString("SorryDave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, more than one item called {0} was found.
        /// </summary>
        internal static string SorryMoreThan_One {
            get {
                return ResourceManager.GetString("SorryMoreThan_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not find that group.
        /// </summary>
        internal static string SorryNoGroup {
            get {
                return ResourceManager.GetString("SorryNoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Enhancement is Off.
        /// </summary>
        internal static string SpeechEnhancementOff {
            get {
                return ResourceManager.GetString("SpeechEnhancementOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Enhancement is On.
        /// </summary>
        internal static string SpeechEnhancementOn {
            get {
                return ResourceManager.GetString("SpeechEnhancementOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting update....
        /// </summary>
        internal static string StartingUpdate {
            get {
                return ResourceManager.GetString("StartingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string StreamConnecting {
            get {
                return ResourceManager.GetString("StreamConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string StreamStarting {
            get {
                return ResourceManager.GetString("StreamStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        internal static string Treble_Text {
            get {
                return ResourceManager.GetString("Treble.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string TypeComposer {
            get {
                return ResourceManager.GetString("TypeComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string TypeGenre {
            get {
                return ResourceManager.GetString("TypeGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string TypePlaylist {
            get {
                return ResourceManager.GetString("TypePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPnP Error {0}.
        /// </summary>
        internal static string UPNP_Error {
            get {
                return ResourceManager.GetString("UPNP_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version_Title {
            get {
                return ResourceManager.GetString("Version_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeButton_Label {
            get {
                return ResourceManager.GetString("VolumeButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A VPN seems to be blocking access to the local network.
        /// </summary>
        internal static string VPNBlocking {
            get {
                return ResourceManager.GetString("VPNBlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string WheelVolume {
            get {
                return ResourceManager.GetString("WheelVolume", resourceCulture);
            }
        }
    }
}
